name = "fingerprintjs-pro-cloudflare-worker"
type = "javascript"

account_id = ""
zone_id = ""
route = ""
workers_dev = true

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
dir = "./dist"
main = "./fingerprintjs-pro-cloudflare-worker.esm.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

